"""Public self-service page. Management secrets stay in URL fragments, never paths."""
import html
import json


def render(route, csrf, sitekey, slug=''):
    state = json.dumps({'path': route['path'].rstrip('/'), 'csrf': csrf, 'slug': slug}, ensure_ascii=True).replace('<', '\\u003c')
    title = html.escape(route.get('title') or 'Личная подписка')
    key = html.escape(sitekey, quote=True)
    return '''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Личная подписка</title>
<style>
:root{color-scheme:dark;font-family:system-ui,-apple-system,sans-serif;background:#101815;color:#eaf3ed}*{box-sizing:border-box}body{margin:0}main{max-width:820px;padding:36px 24px 64px;margin:auto}.brand{font-size:14px;color:#afdcc1;letter-spacing:.04em;margin-bottom:44px}.brand b{display:inline-grid;place-items:center;width:34px;height:34px;border-radius:11px;background:#b5eccd;color:#1c3828;margin-right:10px}h1{font-size:clamp(30px,6vw,46px);letter-spacing:-1.5px;line-height:1.12;margin:12px 0 20px}h2{font-size:20px;margin:0 0 12px}.lead{color:#abbeb1;line-height:1.8;max-width:640px}.pill{display:inline-block;border:1px solid #3b5545;border-radius:99px;padding:7px 12px;font-size:12px;color:#b5eccd}.card{border:1px solid #304138;background:#19241e;padding:26px;border-radius:18px;margin:24px 0}label{display:block;font-size:13px;color:#c5d7cb;margin:18px 0 8px}input{width:100%;background:#111c15;border:1px solid #40574a;border-radius:9px;color:#eef6f0;padding:12px;font:inherit}button,.button{display:inline-block;background:#b5eccd;color:#173624;border:1px solid #b5eccd;border-radius:9px;padding:12px 18px;font:600 13px system-ui;cursor:pointer;text-decoration:none}button:disabled{opacity:.5;cursor:wait}.secondary{background:transparent;color:#c4dfcd;border-color:#496552}.actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:20px}.choices{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:16px 0}.choice{display:flex;align-items:center;gap:12px;margin:0;padding:15px;border:1px solid #3a5042;border-radius:10px;cursor:pointer;overflow-wrap:anywhere}.choice input{width:18px;height:18px;accent-color:#b5eccd;flex:none}.choice:has(input:checked){border-color:#a2d4b6;background:#b5eccd0b}small{display:block;color:#9ab3a2;line-height:1.6;margin:8px 0}.notice{padding:14px 18px;border-radius:10px;border:1px solid #6d5140;background:#30261e;color:#f7d6b5;line-height:1.6;margin:18px 0}.success{border-color:#447153;color:#c5efd3;background:#1c3022}[hidden]{display:none!important}:focus-visible{outline:2px solid #c8fada;outline-offset:3px}.steps{display:flex;gap:18px;color:#97b3a1;font-size:12px;padding:20px 0;border-bottom:1px solid #304138}.steps b{color:#cfebd9;margin-right:7px}.cf-turnstile{margin-top:20px}footer{color:#88a591;font-size:12px;margin-top:32px}#status{white-space:pre-wrap}.count{font-size:12px;color:#a3c3af}.copyfield{font-size:12px}details{margin-top:16px}summary{cursor:pointer;color:#b5eccd;font-size:13px}@media(max-width:540px){main{padding:24px 16px}.card{padding:20px}.choices{grid-template-columns:1fr}.steps{gap:12px;font-size:11px}.brand{margin-bottom:30px}}
</style></head><body><main><div class="brand"><b>sc</b> SUB CLUSTER</div><span class="pill">1 личная ссылка = 1 устройство</span><h1>Ваш VPN.<br>Только нужные серверы.</h1><p class="lead">''' + title + ''' — получите свою личную ссылку, выберите удобные серверы и добавьте подписку в VPN-клиент. Личные ссылки и проверка Cloudflare помогают защитить сервис от ботов.</p><div class="steps"><span><b>01</b>Представьтесь</span><span><b>02</b>Выберите серверы</span><span><b>03</b>Получите ссылку</span></div>
<div id="status" class="notice" role="status" aria-live="polite" hidden></div>
<section id="result" class="card" hidden><h2>Ваша подписка готова</h2><p class="lead">Добавьте эту ссылку в VPN-клиент на нужном устройстве. Она привяжется к нему при первом запросе подписки. На другом устройстве ссылка работать не будет.</p><label for="subscription">Ссылка для VPN-клиента</label><input id="subscription" class="copyfield" readonly><div class="actions"><button type="button" id="copy-sub">Скопировать ссылку</button></div><label for="management">Секретная ссылка управления</label><input id="management" class="copyfield" readonly><small>Сохраните её: она позволяет менять выбор серверов. Не передавайте её другим. Ссылка также сохранена в этом браузере.</small><div class="actions"><button type="button" class="secondary" id="copy-manage">Скопировать управление</button><a class="button secondary" id="manage-link">Управлять серверами</a></div><div class="notice">Одна ссылка — одно устройство. Для второго устройства создайте отдельную подписку. Используйте клиент с поддержкой ID устройства (HWID) без IP-адреса в HWID, например Happ.</div></section>
<section id="saved" class="card" hidden><h2>Ваши ссылки в этом браузере</h2><div id="saved-links" class="actions"></div></section>
<form id="personal-form" class="card"><h2 id="form-title">Создать личную подписку</h2><div id="identity"><label for="name">Ваше имя</label><input id="name" maxlength="80" autocomplete="given-name" placeholder="Как к вам обращаться" required><label for="slug">Название ссылки <span class="count">необязательно</span></label><input id="slug" pattern="[A-Za-z0-9_-]{4,64}" maxlength="64" placeholder="Например, alex-phone"><small>4–64 латинских букв, цифр, дефисов или подчёркиваний. Оставьте пустым для случайной, трудной для угадывания ссылки. Название не является паролем.</small></div><label for="filter">Какие серверы оставить в VPN?</label><input type="search" id="filter" placeholder="Найти сервер"><div class="actions"><button type="button" class="secondary" id="all">Выбрать все</button><button type="button" class="secondary" id="none">Снять выбор</button></div><div id="choices" class="choices"></div><div id="count" class="count" aria-live="polite"></div><small>Группы и роутеры выбираются целиком. Если состав сервера изменится, может потребоваться выбрать его заново.</small><div id="captcha" class="cf-turnstile" data-sitekey="''' + key + '''" data-action="personal_create" data-theme="dark"></div><div class="actions"><button id="submit" type="submit" disabled>Получить личную ссылку</button></div></form><footer>Не делитесь личной ссылкой. Управление доступно только по секретной ссылке, полученной при создании.</footer></main>
<script>const PAGE=''' + state + ''';</script><script>
(()=>{'use strict';const $=id=>document.getElementById(id);let token=new URLSearchParams(location.hash.slice(1)).get('manage')||'';let selected=new Set(),catalog=[],ready=false;const storeKey='personal-links:'+PAGE.path;
function message(text,ok=false){$('status').textContent=text;$('status').hidden=false;$('status').classList.toggle('success',ok)}
async function request(op,data={}){const res=await fetch(PAGE.path,{method:'POST',headers:{'Content-Type':'application/json','X-Portal-CSRF':PAGE.csrf},body:JSON.stringify({op,slug:PAGE.slug,token,...data})});let body;try{body=await res.json()}catch(e){throw new Error('Сервис временно недоступен. Попробуйте позже.')}if(!res.ok||!body.ok)throw new Error(body.error||'Не удалось выполнить запрос');return body}
function count(){$('count').textContent='Выбрано: '+selected.size+' из '+catalog.length;$('submit').disabled=selected.size===0||!ready}
function draw(){const query=$('filter').value.toLocaleLowerCase();$('choices').replaceChildren();catalog.filter(x=>x.name.toLocaleLowerCase().includes(query)).forEach(item=>{const label=document.createElement('label');label.className='choice';const input=document.createElement('input');input.type='checkbox';input.checked=selected.has(item.id);input.addEventListener('change',()=>{input.checked?selected.add(item.id):selected.delete(item.id);count()});label.append(input,document.createTextNode(item.name));$('choices').append(label)});count()}
function saved(){try{const entries=JSON.parse(localStorage.getItem(storeKey)||'[]');$('saved-links').replaceChildren();entries.filter(x=>typeof x.slug==='string'&&/^[A-Za-z0-9_-]{4,64}$/.test(x.slug)&&typeof x.token==='string').forEach(x=>{const a=document.createElement('a');a.className='button secondary';a.textContent=x.name;a.href=PAGE.path+'/'+x.slug+'#manage='+encodeURIComponent(x.token);$('saved-links').append(a)});$('saved').hidden=!$('saved-links').children.length}catch(e){}}
$('filter').addEventListener('input',draw);$('all').onclick=()=>{selected=new Set(catalog.map(x=>x.id));draw()};$('none').onclick=()=>{selected.clear();draw()};
async function copy(id){try{await navigator.clipboard.writeText($(id).value);message('Ссылка скопирована.',true)}catch(e){$(id).focus();$(id).select();message('Скопируйте выделенную ссылку вручную.')}}$('copy-sub').onclick=()=>copy('subscription');$('copy-manage').onclick=()=>copy('management');
$('personal-form').addEventListener('submit',async event=>{event.preventDefault();$('submit').disabled=true;try{if(PAGE.slug){await request('update',{selected:[...selected]});message('Выбор сохранён. Обновите подписку в VPN-клиенте.',true)}else{const captcha=document.querySelector('[name="cf-turnstile-response"]');const result=await request('create',{name:$('name').value,slug:$('slug').value,selected:[...selected],captcha:captcha?captcha.value:''});const url=location.origin+PAGE.path+'/'+result.slug;const management=url+'#manage='+encodeURIComponent(result.token);$('subscription').value=url;$('management').value=management;$('manage-link').href=management;$('result').hidden=false;$('personal-form').hidden=true;try{const entries=JSON.parse(localStorage.getItem(storeKey)||'[]');entries.push({slug:result.slug,token:result.token,name:result.name});localStorage.setItem(storeKey,JSON.stringify(entries.slice(-50)))}catch(e){}saved();$('result').scrollIntoView({behavior:'smooth'});message('Личная ссылка создана. Сохраните обе ссылки.',true)}}catch(e){message(e.message);if(window.turnstile&&!PAGE.slug)window.turnstile.reset()}finally{count()}});
async function init(){saved();if(PAGE.slug){$('identity').hidden=true;$('name').required=false;$('captcha').remove();$('submit').textContent='Сохранить выбор';$('form-title').textContent='Управление подпиской';if(!token){$('personal-form').hidden=true;message('Это ссылка для VPN-клиента. Для изменения серверов откройте секретную ссылку управления, полученную при создании.');return}}
try{const result=await request(PAGE.slug?'manage':'catalog');ready=!!PAGE.slug||result.configured;catalog=result.items;selected=new Set((result.selected||catalog.map(x=>x.id)).filter(id=>catalog.some(x=>x.id===id)));draw();if(!catalog.length)message('Сейчас нет доступных серверов. Попробуйте позже.');if(PAGE.slug)message(result.bound?'Ссылка уже привязана к устройству. Вы можете менять выбор серверов.':'Ссылка ещё не привязана. Добавьте её в VPN-клиент на нужном устройстве.',true);else if(!result.configured){$('submit').disabled=true;message('Администратор ещё не настроил Cloudflare Turnstile. Создание ссылок пока недоступно.')}}catch(e){$('submit').disabled=true;message(e.message)}}init();})();
</script>''' + ('''<script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>''' if sitekey and not slug else '') + '</body></html>'
